package com.studyplanner.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.List;

/**
 * StudyPlan — stores an AI-generated study plan in MongoDB.
 *
 * <p>Created by {@code POST /api/ai/generate-study-plan}. The raw Groq
 * response is parsed into structured sections before being persisted.</p>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "studyPlans")
public class StudyPlan {

    @Id
    private String id;

    /** Owning user. Indexed for fast per-user queries. */
    @Indexed
    private String userId;

    // ── Input parameters echoed for context ─────────────────────────────────
    private List<String> subjects;
    private List<String> examDates;
    private int          dailyStudyHours;
    private List<String> weakTopics;

    // ── AI-generated content ─────────────────────────────────────────────────

    /** Day-by-day study schedule (list of schedule lines). */
    private List<String> dailySchedule;

    /** Revision milestones and spaced-repetition recommendations. */
    private List<String> revisionPlan;

    /** Topics ranked by urgency / difficulty for this user. */
    private List<String> priorityTopics;

    /** Motivational tips generated by the AI. */
    private List<String> motivationTips;

    /** Full raw text returned by the Groq model (for debugging / re-parsing). */
    private String rawResponse;

    /** Groq model used (e.g. "llama3-8b-8192"). */
    private String modelUsed;

    @Indexed
    @CreatedDate
    private LocalDateTime createdAt;
}
